# Generated by Django 4.1.1 on 2022-12-30 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('İstanbul(Anadolu)', 'İstanbul(Anadolu)'), ('İstanbul(Avrupa)', 'İstanbul(Avrupa)'), ('Ankara', 'Ankara'), ('Bursa', 'Bursa'), ('İzmir', 'İzmir'), ('Adana', 'Adana'), ('Adıyaman', 'Adıyaman'), ('Afyonkarahisar', 'Afyonkarahisar'), ('Ağrı', 'Ağrı'), ('Aksaray', 'Aksaray')], max_length=27, verbose_name='city')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='company_name')),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Pasif', 'Pasif')], default='Pasif', max_length=5, verbose_name='company_status')),
                ('address', models.TextField(max_length=150, verbose_name='adress')),
                ('idcity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.city', verbose_name='idcity')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Türkiye', 'Türkiye'), ('Almanya', 'Almanya'), ('Amerika Birleşik Devletleri', 'Amerika Birleşik Devletleri'), ('Arjantin', 'Arjantin'), ('Azerbaycan', 'Azerbaycan'), ('Brezilya', 'Brezilya'), ('Bulgaristan', 'Bulgaristan'), ('Danimarka', 'Danimarka'), ('Fransa', 'Fransa'), ('Gürcistan', 'Gürcistan'), ('Hollanda', 'Hollanda'), ('Irak', 'Irak'), ('İngiltere', 'İngiltere'), ('İran', 'İran'), ('İspanya', 'İspanya'), ('İtalya', 'İtalya'), ('Uruguay', 'Uruguay')], default='Türkiye', max_length=27, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Acil Servis', 'Acil Servis'), ('Algoloji', 'Algoloji'), ('Aile Hekimliği', 'Aile Hekimliği'), ('Amatem', 'Amatem(Alkol ve Madde Bağımlığı)'), ('Anesteziyoloji ve Reanimasyon', 'Anesteziyoloji ve Reanimasyon'), ('Beyin ve Sinir Cerrahisi', 'Beyin ve Sinir Cerrahisi'), ('Cerrahi Onkolojisi', 'Cerrahi Onkolojisi'), ('Çocuk Bölümü', 'Çocuk Bölümü'), ('Çocuk Diş Hekimliği', 'Çocuk Diş Hekimliği'), ('Cildiye', 'Deri ve Zührevi Hastalıkları'), ('Diş Hekimliği', 'Diş Hekimliği'), ('Endodonti', 'Endodonti'), ('Endokrin', 'Endokrinoloji ve Metabolizma Hastalıkları'), ('Enfeksiyon', 'Enfeksiyon Hastalıkları ve Klinik Mikrobiyoloji'), ('Fiziksel Tıp ve Rehabilitasyon', 'Fiziksel Tıp ve Rehabilitasyon'), ('Gastroenteroloji', 'Gastroenteroloji'), ('Gelişimsel Pediatri', 'Gelişimsel Pediatri'), ('Genel Cerrahi', 'Genel Cerrahi'), ('Geriatri', 'Geriatri'), ('Göğüs Cerrahisi', 'Göğüs Cerrahisi'), ('Göz Hastalıkları', 'Göz Hastalıkları'), ('Hematoloji', 'Hematoloji'), ('İç Hastalıkları(Dahiliye)', 'İç Hastalıkları(Dahiliye)'), ('İmmünoloji ve Alerji Hastalıkları', 'İmmünoloji ve Alerji Hastalıkları'), ('İş ve Mesleki Hastalıkları', 'İş ve Mesleki Hastalıkları'), ('Kadın Hastalıkları ve Doğum', 'Kadın Hastalıkları ve Doğum'), ('Kalp ve Damar Cerrahisi', 'Kalp ve Damar Cerrahisi'), ('Kulak Burun Boğaz Hastalıkları', 'Kulak Burun Boğaz Hastalıkları'), ('Nefroloji', 'Nefroloji'), ('Nöroloji', 'Nöroloji'), ('Ordodonti', 'Ordodonti'), ('Perinatoloji', 'Perinatoloji'), ('Plastik Rekonstrüktif Estetik Cerrahi', 'Plastik Rekonstrüktif Estetik Cerrahi'), ('Ruh Sağlığı ve Hastalıkları(Psikiyatri)', 'Ruh Sağlığı ve Hastalıkları(Psikiyatri)'), ('Üroloji', 'Üroloji'), ('Radyoloji', 'Radyoloji')], max_length=50, verbose_name='department_name')),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Pasif', 'Pasif')], max_length=6, verbose_name='department_status')),
                ('idcompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.company', verbose_name='dprt_company')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Öneri', 'öneri'), ('Şikayet', 'Şikayet'), ('Teşekkür', 'Teşekkür')], max_length=8, verbose_name='f_type_name')),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Pasif', 'Pasif')], max_length=6, verbose_name='f_type_status')),
                ('idcompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.company', verbose_name='f_type_company')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Personel', 'Personel'), ('Hijyen', 'Hijyen'), ('Fiyat', 'Fiyat')], max_length=35, verbose_name='f_source_name')),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Pasif', 'Pasif')], max_length=6, verbose_name='f_source_status')),
                ('idcompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.company', verbose_name='f_source_company')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Kötü Davranış', 'Kötü Davranış'), ('Hijyen Azlığı', 'Hijyen Azlığı'), ('Personelin Tutum ve Davranışı', 'Personelin Tutum ve Davranışı'), ('Personel Azlığı', 'Personel Azlığı'), ('Refakatçi İmkanı', 'Refaketçi İmkanı'), ('Hastane Olanakları', 'Hastane Olanakları'), ('Diğer', 'Diğer')], max_length=35, verbose_name='f_reason_name')),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Pasif', 'Pasif')], max_length=6, verbose_name='f_reason_status')),
                ('idcompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.company', verbose_name='f_reason_company')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackPriorityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Normal', 'Normal'), ('Orta', 'Orta'), ('Yüksek', 'Yüksek')], max_length=35, verbose_name='f_priority_name')),
                ('idcompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.company', verbose_name='f_priority_company')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackPersonel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Doktor', 'Doktor'), ('Hemşire', 'Hemşire'), ('Eczacı', 'Eczacı'), ('Diş Hekimi', 'Diş Hekimi'), ('Fizyoterapist', 'Fizyoterapist'), ('Ebe', 'Ebe'), ('Anestezi Teknikeri', 'Anestezi Teknikeri'), ('Laboratuvar Teknikeri', 'Laboratuvar Teknikeri'), ('Odyometri Teknikeri', 'Odyometri Teknikeri'), ('Ameliyathane Teknikeri', 'Ameliyathane Teknikeri'), ('Radyoloji Teknikeri', 'Radyoloji Teknikeri'), ('Sekreter', 'Sekreter'), ('Temizlik Personeli', 'Temizlik Personeli'), ('Günevlik', 'Güvenlik'), ('Hasta Bakıcı', 'Hasta Bakıcı'), ('Diğer', 'Diğer')], max_length=35, verbose_name='f_personel_name')),
                ('idcompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.company', verbose_name='f_personel_company')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True, verbose_name='name')),
                ('Surname', models.CharField(blank=True, max_length=30, null=True, verbose_name='surname')),
                ('Email', models.EmailField(max_length=40, verbose_name='email')),
                ('Content', models.TextField(verbose_name='content')),
                ('Photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='photo')),
                ('FeedbackOpenDate', models.DateTimeField(auto_now_add=True)),
                ('FeedbackClosedDate', models.DateTimeField(auto_now_add=True)),
                ('DurationTime', models.CharField(max_length=100, verbose_name='duration_time')),
                ('IdCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.company', verbose_name='feedback_company')),
                ('IdDepartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.department', verbose_name='f_department')),
                ('IdFeedbackPersonel', models.ManyToManyField(to='feedback.feedbackpersonel')),
                ('IdFeedbackPriorityLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbackprioritylevel', verbose_name='f_priority_level')),
                ('IdFeedbackReason', models.ManyToManyField(to='feedback.feedbackreason')),
                ('IdFeedbackSource', models.ManyToManyField(to='feedback.feedbacksource')),
                ('IdFeedbackType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbacktype', verbose_name='f_type')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='idcountry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.country', verbose_name='idcountry'),
        ),
        migrations.AddField(
            model_name='city',
            name='IdCountry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.country', verbose_name='country'),
        ),
    ]
