# Generated by Django 4.1.1 on 2023-02-08 10:38

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedbackstatushistory_feedbackstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='PhoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='feedbackstatus',
            name='name',
            field=models.CharField(choices=[('Açık', 'Açık'), ('İşlemde', 'İşlemde'), ('Çözüldü', 'Çözüldü')], max_length=7, verbose_name='f_status_name'),
        ),
        migrations.AlterField(
            model_name='feedbackstatushistory',
            name='history_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbackstatus', verbose_name='history_status'),
        ),
    ]
