# Generated by Django 4.1.1 on 2023-02-08 11:50

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedback_phonenumber_alter_feedbackstatus_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ad')),
                ('Surname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Soyad')),
                ('Email', models.EmailField(max_length=40, verbose_name='Email')),
                ('PhoneNumber', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, verbose_name='Telefon Numarası')),
                ('Content', models.TextField(verbose_name='Talep-Şİkayet İçeriği')),
                ('Photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Resim')),
                ('IdCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.company', verbose_name='Hastane')),
                ('IdDepartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.department', verbose_name='Talep-Şikayet Departmanı')),
                ('IdFeedbackPersonel', models.ManyToManyField(to='feedback.feedbackpersonel', verbose_name='Talep-Şikayet Personeli (Çoklu Seçim Yapılabilir) ')),
                ('IdFeedbackReason', models.ManyToManyField(to='feedback.feedbackreason', verbose_name='Talep-Şikayet Nedeni (Detay) (Çoklu Seçim Yapılabilir) ')),
                ('IdFeedbackSource', models.ManyToManyField(to='feedback.feedbacksource', verbose_name='Talep-Şikayet Nedeni (Çoklu Seçim Yapılabilir) ')),
                ('IdFeedbackType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbacktype', verbose_name='Talep-Şikayet Tipi')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeedbackOpenDate', models.DateTimeField(auto_now_add=True)),
                ('FeedbackClosedDate', models.DateTimeField(auto_now_add=True)),
                ('DurationTime', models.CharField(max_length=100, verbose_name='duration_time')),
                ('IdFeedbackPriorityLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbackprioritylevel', verbose_name='f_priority_level')),
                ('IdFeedbackUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbackuser', verbose_name='f_id')),
            ],
        ),
        migrations.AlterField(
            model_name='feedbackstatushistory',
            name='history_feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbackdepartment', verbose_name='history_feedback'),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
