# Generated by Django 4.1.1 on 2023-02-09 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedbackuser_feedbackdepartment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackdepartment',
            name='FeedbackOpenDate',
        ),
        migrations.AddField(
            model_name='feedbackuser',
            name='FeedbackOpenDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
            preserve_default=False,
        ),
    ]
