# Generated by Django 4.1.1 on 2023-02-13 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_feedbackdepartment_lastsolvedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackdepartment',
            name='FeedbackStatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbackstatus', verbose_name='Talep-Şikayet Durumu'),
        ),
        migrations.AlterField(
            model_name='feedbackstatushistory',
            name='history_feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbackuser', verbose_name='history_feedback'),
        ),
    ]
