# Generated by Django 4.1.1 on 2023-02-15 10:01

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_alter_feedbackdepartment_idfeedbackuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ad')),
                ('Surname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Soyad')),
                ('Email', models.EmailField(max_length=40, verbose_name='Email')),
                ('PhoneNumber', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, verbose_name='Telefon Numarası')),
                ('Content', models.TextField(verbose_name='Talep-Şİkayet İçeriği')),
                ('Photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Resim')),
                ('FeedbackOpenDate', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('FeedbackClosedDate', models.DateTimeField(auto_now_add=True, verbose_name='Talep-Şikayet Son İşlem Saati')),
                ('LastSolveDate', models.CharField(blank=True, max_length=100, verbose_name='Talep ve Şikayetin Yanıtı İçin Gerekli Zaman(Gün)')),
                ('DurationTime', models.CharField(blank=True, max_length=100, verbose_name='Geçen Süre')),
                ('IdCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.company', verbose_name='Hastane')),
                ('IdDepartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.department', verbose_name='Talep-Şikayet Departmanı')),
                ('IdFeedbackPersonel', models.ManyToManyField(to='feedback.feedbackpersonel', verbose_name='Talep-Şikayet Personeli (Çoklu Seçim Yapılabilir) ')),
                ('IdFeedbackPriorityLevel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbackprioritylevel', verbose_name='Talep-Şikayet Öncelik Seviyesi')),
                ('IdFeedbackReason', models.ManyToManyField(to='feedback.feedbackreason', verbose_name='Talep-Şikayet Nedeni (Detay) (Çoklu Seçim Yapılabilir) ')),
                ('IdFeedbackSource', models.ManyToManyField(to='feedback.feedbacksource', verbose_name='Talep-Şikayet Nedeni (Çoklu Seçim Yapılabilir) ')),
                ('IdFeedbackType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbacktype', verbose_name='Talep-Şikayet Tipi')),
            ],
        ),
        migrations.RemoveField(
            model_name='feedbackuser',
            name='IdCompany',
        ),
        migrations.RemoveField(
            model_name='feedbackuser',
            name='IdDepartment',
        ),
        migrations.RemoveField(
            model_name='feedbackuser',
            name='IdFeedbackPersonel',
        ),
        migrations.RemoveField(
            model_name='feedbackuser',
            name='IdFeedbackReason',
        ),
        migrations.RemoveField(
            model_name='feedbackuser',
            name='IdFeedbackSource',
        ),
        migrations.RemoveField(
            model_name='feedbackuser',
            name='IdFeedbackType',
        ),
        migrations.DeleteModel(
            name='FeedbackDepartment',
        ),
        migrations.AlterField(
            model_name='feedbackstatushistory',
            name='history_feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedback', verbose_name='history_feedback'),
        ),
        migrations.DeleteModel(
            name='FeedbackUser',
        ),
    ]
