# Generated by Django 4.1.1 on 2023-02-15 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_feedback_remove_feedbackuser_idcompany_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='DurationTime',
            field=models.CharField(max_length=100, null=True, verbose_name='Geçen Süre'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='IdFeedbackPriorityLevel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbackprioritylevel', verbose_name='Talep-Şikayet Öncelik Seviyesi'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='LastSolveDate',
            field=models.CharField(max_length=100, null=True, verbose_name='Talep ve Şikayetin Yanıtı İçin Gerekli Zaman(Gün)'),
        ),
    ]
