# Generated by Django 4.1.1 on 2023-02-15 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0011_alter_feedback_durationtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='IdFeedbackStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbackstatus', verbose_name='Talep-Şikayet Durumu'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='DurationTime',
            field=models.CharField(max_length=100, null=True, verbose_name='Geçen Zaman'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='FeedbackClosedDate',
            field=models.DateTimeField(auto_now=True, verbose_name='Talep-Şikayet Son İşlem Saati'),
        ),
        migrations.AlterField(
            model_name='feedbackstatushistory',
            name='history_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Geri Bildirim Tarihi'),
        ),
        migrations.AlterField(
            model_name='feedbackstatushistory',
            name='history_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.department', verbose_name='Talep-Şikayet Departmanı'),
        ),
        migrations.AlterField(
            model_name='feedbackstatushistory',
            name='history_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Geri Bildirim İçin Dosya'),
        ),
        migrations.AlterField(
            model_name='feedbackstatushistory',
            name='history_note',
            field=models.TextField(null=True, verbose_name='Geri Bildirim Notu'),
        ),
        migrations.AlterField(
            model_name='feedbackstatushistory',
            name='history_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbackstatus', verbose_name='Talep-Şikayet Durumu'),
        ),
        migrations.AlterField(
            model_name='feedbackstatushistory',
            name='history_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Talep-Şikayet Kontrolü Yapan Kişi'),
        ),
    ]
