# Generated by Django 4.1.1 on 2023-02-25 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_feedback_idfeedbackstatus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-FeedbackOpenDate']},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Content',
            field=models.TextField(verbose_name='Talep-Şikayet İçeriği'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='IdFeedbackStatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbackstatus', verbose_name='Talep-Şikayet Durumu'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='LastSolveDate',
            field=models.IntegerField(null=True, verbose_name='Talep ve Şikayetin Yanıtı İçin Gerekli Zaman(Gün)'),
        ),
        migrations.AlterField(
            model_name='feedbackpersonel',
            name='name',
            field=models.CharField(choices=[('Doktor', 'Doktor'), ('Hemşire', 'Hemşire'), ('Eczacı', 'Eczacı'), ('Diş Hekimi', 'Diş Hekimi'), ('Fizyoterapist', 'Fizyoterapist'), ('Ebe', 'Ebe'), ('Anestezi Teknikeri', 'Anestezi Teknikeri'), ('Laboratuvar Teknikeri', 'Laboratuvar Teknikeri'), ('Odyometri Teknikeri', 'Odyometri Teknikeri'), ('Ameliyathane Teknikeri', 'Ameliyathane Teknikeri'), ('Radyoloji Teknikeri', 'Radyoloji Teknikeri'), ('Sekreter', 'Sekreter'), ('Temizlik Personeli', 'Temizlik Personeli'), ('Güvenlik', 'Güvenlik'), ('Hasta Bakıcı', 'Hasta Bakıcı'), ('Diğer', 'Diğer')], max_length=35, verbose_name='f_personel_name'),
        ),
        migrations.AlterField(
            model_name='feedbackstatushistory',
            name='history_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Geri Bildirim Dosyası'),
        ),
    ]
