# Generated by Django 4.1.1 on 2023-03-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0013_alter_feedback_options_alter_feedback_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-FeedbackOpenDate', '-IdFeedbackPriorityLevel']},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='DurationTime',
            field=models.IntegerField(null=True, verbose_name='Geçen Zaman(Gün)'),
        ),
    ]
