# Generated by Django 4.1.1 on 2023-03-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0014_alter_feedback_options_alter_feedback_durationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='LastSolveDate',
            field=models.DateTimeField(null=True, verbose_name='Talep ve Şikayetin Yanıtı İçin Gerekli Gün'),
        ),
    ]
