# Generated by Django 4.1.1 on 2023-03-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0015_alter_feedback_lastsolvedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='DurationTime',
            field=models.CharField(max_length=100, null=True, verbose_name='Geçen Zaman'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='LastSolveDate',
            field=models.DateTimeField(null=True, verbose_name='Talep ve Şikayetin Yanıtı İçin Gerekli Gün(Ör: ../../.... 17:40)'),
        ),
    ]
