# Generated by Django 4.1.1 on 2023-03-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0016_alter_feedback_durationtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=27, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default='Türkiye', max_length=27, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50, verbose_name='department_name'),
        ),
        migrations.AlterField(
            model_name='feedbackpersonel',
            name='name',
            field=models.CharField(max_length=35, verbose_name='f_personel_name'),
        ),
        migrations.AlterField(
            model_name='feedbackreason',
            name='name',
            field=models.CharField(max_length=35, verbose_name='f_reason_name'),
        ),
        migrations.AlterField(
            model_name='feedbacksource',
            name='name',
            field=models.CharField(max_length=35, verbose_name='f_source_name'),
        ),
        migrations.AlterField(
            model_name='feedbacktype',
            name='name',
            field=models.CharField(max_length=8, verbose_name='Talep-Şikayet Tipi'),
        ),
        migrations.AlterField(
            model_name='feedbacktype',
            name='status',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Pasif', 'Pasif')], max_length=6, verbose_name='Statü'),
        ),
    ]
