# Generated by Django 4.1.1 on 2023-02-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddprofile',
            name='user_status',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Pasif', 'Pasif')], max_length=5, verbose_name='user_status'),
        ),
    ]
