# Generated by Django 4.1.1 on 2023-03-15 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0017_alter_city_name_alter_country_name_and_more'),
        ('user', '0002_alter_useraddprofile_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullancı Adı'),
        ),
        migrations.AlterField(
            model_name='useraddprofile',
            name='user_adress',
            field=models.TextField(max_length=100, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='useraddprofile',
            name='user_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.city', verbose_name='Şehir'),
        ),
        migrations.AlterField(
            model_name='useraddprofile',
            name='user_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.company', verbose_name='Hastane'),
        ),
        migrations.AlterField(
            model_name='useraddprofile',
            name='user_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.country', verbose_name='Ülke'),
        ),
        migrations.AlterField(
            model_name='useraddprofile',
            name='user_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.department', verbose_name='Departman'),
        ),
        migrations.AlterField(
            model_name='useraddprofile',
            name='user_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='useraddprofile',
            name='user_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userroles', verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='useraddprofile',
            name='user_status',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Pasif', 'Pasif')], max_length=5, verbose_name='Statü'),
        ),
    ]
